.TH ARTICLES 1
.SH NAME
articles \- process articles
.SH SYNOPSIS
.B articles
[\fB\-m]
[\fB\-\-markdown]
[\fB\-t]
[\fB\-\-tex]
[\fB\-a]
[\fB\-\-all]
.SH DESCRIPTION
.B articles
processes articles and generates HTML files by default.
Input must be redirected by STDIN.
.SH OPTIONS
.TP
.BR \-m ", " \-\-markdown
Generate Markdown files.
.TP
.BR \-t ", " \-\-tex
Generate Tex files.
.TP
.BR \-a ", " \-\-all
Generate Tex, Markdown and HTML files.
